version: '3.4'

services:
  app:
    image: proxy-http-server-client-app
    container_name: proxy-http-server-client-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8001:8080
    volumes:
      - ./.bin/:/root/

  debug:
    image: proxy-http-server-client-debug
    container_name: proxy-http-server-client-debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8000:8000"
      - "2345:2345"
    volumes:
      - ./.bin/:/root/